name: myapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0
  intl: ^0.19.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  flutter_localizations:
    sdk: flutter
  logger: ^2.4.0
  shared_preferences: ^2.2.3
  country_flags: ^3.0.0
  flutter_svg: ^2.0.10+1
  sqflite_common_ffi: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  fonts:
  - family: Noto-Sans
    fonts:
      - asset: asset/fonts/NotoSans-Regular.ttf
      - asset: asset/fonts/NotoSans-Bold.ttf
        weight: 700

  assets:
    - asset/pics/putting_green.jpg
    - asset/pics/page1_background.png
    - asset/pics/page1_background.svg
    - asset/pics/icons_page1/Drill1.svg
    - asset/pics/icons_page1/Drill2.svg 
    - asset/pics/icons_page1/Drill3.svg
    - asset/pics/icons_page1/Drill4.svg
    - asset/pics/icons_page1/Drill5.svg
    - asset/pics/Symbol_Drill1.png  
    - asset/pics/Symbol_Drill2.png
    - asset/pics/Symbol_Drill3.png
    - asset/pics/Symbol_Drill4.png
    - asset/pics/Symbol_Drill5.png
    - asset/pics/thePreparePic1.jpg
    - asset/pics/thePreparePic2.jpg
    - asset/pics/thePreparePic3.jpg
    - asset/pics/thePreparePic4.jpg
    - asset/pics/thePreparePic5.jpg
    - asset/pics/theExercisePic1.png
    - asset/pics/theExercisePic2.png
    - asset/pics/theExercisePic3.png
    - asset/pics/theExercisePic4.png
    - asset/pics/theExercisePic5.png

