name: myapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0
  intl: ^0.19.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  flutter_localizations:
    sdk: flutter
  logger: ^2.4.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  generate: true

  fonts:
  - family: Noto-Sans
    fonts:
      - asset: asset/fonts/NotoSans-Regular.ttf
      - asset: asset/fonts/NotoSans-Bold.ttf
        weight: 700

  assets:
    - asset/pics/Drill1.png
    - asset/pics/Drill2.png
    - asset/pics/Drill3.png
    - asset/pics/Drill4.png
    - asset/pics/Drill5.png

